
spring:
  application:
    name: member-api


server:
  port: 8089


eureka:
  client:
    service-url:
      defaultZone: http://hero:123456@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
    # 默认 90 秒
    lease-expiration-duration-in-seconds: 5
    # 默认 30 秒
    lease-renewal-interval-in-seconds: 5


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: refresh,health,info


feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true
turbine:
# 配置需要聚合的服务名称
  app-config: member-api
# Turbine需要聚合的集群名称
  aggregator:
    cluster-config: default
# 集群名表达式
  cluster-name-expression: new String("default")

