
spring:
  application:
    name: member-api

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://hero:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}